In [1]:
import torch

In [2]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
torch.ones([3, 4, 2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [4]:
torch.Tensor([[1, 2, 3, 4],
              [5, 6, 7, 7]])

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 7.]])

In [5]:
x = torch.Tensor([[1, 2, 3, 4],
                 [5, 6, 7, 7]])

In [6]:
x.shape

torch.Size([2, 4])

In [8]:
x.size()

torch.Size([2, 4])

In [10]:
x[0][2]

tensor(3.)

In [11]:
x[0, 2]

tensor(3.)

In [12]:
x ** 2

tensor([[ 1.,  4.,  9., 16.],
        [25., 36., 49., 49.]])

In [13]:
x + 1

tensor([[2., 3., 4., 5.],
        [6., 7., 8., 8.]])

In [20]:
y = torch.tensor([[ 1.,  4.,  9., 16.],
        [25., 36., 49., 49.]])

In [21]:
x + y

tensor([[ 2.,  6., 12., 20.],
        [30., 42., 56., 56.]])

In [22]:
x * y

tensor([[  1.,   8.,  27.,  64.],
        [125., 216., 343., 343.]])

In [23]:
x / y

tensor([[1.0000, 0.5000, 0.3333, 0.2500],
        [0.2000, 0.1667, 0.1429, 0.1429]])

In [24]:
x % y

tensor([[0., 2., 3., 4.],
        [5., 6., 7., 7.]])

In [25]:
x > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True]])

In [26]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 1.9459]])

In [27]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.6570]])

In [28]:
mask = x > 3

In [29]:
mask 

tensor([[False, False, False,  True],
        [ True,  True,  True,  True]])

In [30]:
x[mask]

tensor([4., 5., 6., 7., 7.])

In [31]:
y = x

In [32]:
y[0, 0] = 999

In [33]:
x

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   7.]])

In [34]:
y

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   7.]])

In [36]:
y = x.clone()
y[0, 0] = 7

In [37]:
x

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   7.]])

In [38]:
y

tensor([[7., 2., 3., 4.],
        [5., 6., 7., 7.]])

In [39]:
x.dtype

torch.float32

In [40]:
x = x.double()

In [41]:
x

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   7.]], dtype=torch.float64)

In [42]:
x.dtype

torch.float64

In [43]:
import numpy as np

In [44]:
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])

In [45]:
x = torch.from_numpy(x)

In [46]:
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]], dtype=torch.int32)

In [47]:
x = x.numpy()

In [48]:
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [49]:
x = torch.rand([2000, 3000])

In [50]:
x

tensor([[0.7952, 0.0035, 0.7263,  ..., 0.8225, 0.0452, 0.7570],
        [0.1807, 0.4049, 0.3781,  ..., 0.7407, 0.0817, 0.0151],
        [0.1573, 0.9793, 0.2936,  ..., 0.4677, 0.0908, 0.3594],
        ...,
        [0.9781, 0.2228, 0.8253,  ..., 0.5201, 0.6726, 0.0654],
        [0.2443, 0.9408, 0.6408,  ..., 0.2205, 0.8694, 0.8483],
        [0.8952, 0.8532, 0.8120,  ..., 0.0399, 0.0987, 0.1619]])

In [51]:
torch.cuda.is_available()

True

In [53]:
device = torch.device('cpu')

In [54]:
device

device(type='cpu')

In [55]:
x_cuda = x.to(device)
x_cuda

tensor([[0.7952, 0.0035, 0.7263,  ..., 0.8225, 0.0452, 0.7570],
        [0.1807, 0.4049, 0.3781,  ..., 0.7407, 0.0817, 0.0151],
        [0.1573, 0.9793, 0.2936,  ..., 0.4677, 0.0908, 0.3594],
        ...,
        [0.9781, 0.2228, 0.8253,  ..., 0.5201, 0.6726, 0.0654],
        [0.2443, 0.9408, 0.6408,  ..., 0.2205, 0.8694, 0.8483],
        [0.8952, 0.8532, 0.8120,  ..., 0.0399, 0.0987, 0.1619]])